#!/bin/bash

# Initialize the module system
. /lrz/sys/share/modules/init/bash

# Needed by the simulation
module load gcc/4.9
module load cmake
module unload mpi.intel
module load mpi.intel/4.1
module load petsc/3.5

# Our python scripts are not compatible with ancient python versions
module load python/3.3_anaconda_nompi

module list

# The default petsc module configuration puts both parts in PETSC_ARCH but the
# CMake-PETSc-module expects the directory and archicture split into two
# variables.
if [[ -z "$PETSC_ARCH" ]]; then
  export PETSC_ARCH=$(basename $PETSC_DIR)
  export PETSC_DIR=$(dirname $PETSC_DIR)
fi
