#!/usr/bin/env python

import fileinput
import itertools
import math
import os
import shutil
import subprocess
import sys
import time
import xml.etree.ElementTree as ET
from argparse import ArgumentParser

# For some documentation see
# http://www.lrz.de/services/compute/linux-cluster/batch_parallel
JOB_TEMPLATE = """#!/bin/bash
#SBATCH -o {out_file}
#SBATCH -D {out_dir}
#SBATCH -J {name}
#SBATCH --get-user-env
#SBATCH --partition={partition}
#SBATCH --ntasks={mpi_num_ranks}
#SBATCH --cpus-per-task={cpus_per_task}
#SBATCH --mail-type=end
#SBATCH --mail-user={notification_email}
#SBATCH --export=NONE
#SBATCH --time={time}

# Load the module system
source /etc/profile.d/modules.sh

mpiexec.hydra -genv OMP_NUM_THREADS 1   \\
              -ppn {processes_per_node} \\
              -n {mpi_num_ranks}        \\
              {ns_executable} {scenario}
"""


def parseArguments():
    parser = ArgumentParser(description="Submit a simulation as a batch job")
    parser.add_argument("-e",
                        "--email",
                        help="Email-Adress to send a notification email to")
    parser.add_argument("-n",
                        "--name",
                        help="Name of job",
                        default="turb-flow")
    parser.add_argument("--intel",
                        action="store_const",
                        const="intel",
                        dest="architecture",
                        default="intel",
                        help="Run on intel nodes")
    parser.add_argument("--amd",
                        action="store_const",
                        const="amd",
                        dest="architecture",
                        help="Run on AMD nodes")
    parser.add_argument("--nx",
                        type=int,
                        help="Number of processes in X direction",
                        default=1)
    parser.add_argument("--ny",
                        type=int,
                        help="Number of processes in Y direction",
                        default=1)
    parser.add_argument("--nz",
                        type=int,
                        help="Number of processes in Z direction",
                        default=1)
    parser.add_argument(
        "--time",
        help="Maximum execution time (e.g. 2:00 for two hours)",
        default="00:10")
    parser.add_argument("--no-timing",
                        help="Disable timing data collection",
                        action="store_false",
                        dest="timing",
                        default=True)
    parser.add_argument("--no-vtk",
                        help="Disable VTK output",
                        action="store_false",
                        dest="vtk",
                        default=True)
    parser.add_argument("--sx",
                        type=int,
                        help="Number of cells in X direction",
                        default=None)
    parser.add_argument("--sy",
                        type=int,
                        help="Number of cells in Y direction",
                        default=None)
    parser.add_argument("--sz",
                        type=int,
                        help="Number of cells in Z direction",
                        default=1)
    parser.add_argument("-l",
                        "--local",
                        action="store_const",
                        const=True,
                        default=False,
                        help="Run on local machine")
    parser.add_argument("--petsc-args",
                        default="petsc_commandline_arg",
                        help="PETSc arguments file")
    parser.add_argument(
        "out",
        help="Directory to store job configuration and results")
    parser.add_argument("executable",
                        help="The executable to run (normally ns)")
    parser.add_argument("scenario", help="A scenario configuration file")

    arguments = parser.parse_args()

    if not arguments.email and not arguments.local:
        parser.error(
            "You need to set your email address to run on the cluster")

    return arguments


def copyPetscArguments(jobdir, argsfile):
    """Copy the petsc_commandline_arg file to the job directory.

    Our code expects a petsc_commandline_arg file in the working directory."""
    shutil.copyfile(argsfile, os.path.join(jobdir, "petsc_commandline_arg"))


def configureScenario(out, templatepath, geometrypath, nx, ny, nz, sx, sy, sz,
                      vtkpath, enable_timing, timingpath, enable_vtk,initial,bakspath):
    """Configure a scenario template for parallel execution.

    The configured scenario is written into `out`."""
    tree = ET.parse(templatepath)
    root = tree.getroot()

    for child in root.findall("parallel"):
        child.attrib["numProcessorsX"] = str(nx)
        child.attrib["numProcessorsY"] = str(ny)
        child.attrib["numProcessorsZ"] = str(nz)

    for child in root.findall("vtk"):
        child.attrib["enabled"] = str(enable_vtk).lower()
        child.text = os.path.join(vtkpath, "vtk")

    for child in root.findall("timing"):
        child.attrib["enabled"] = str(enable_timing).lower()
        child.text = timingpath
    else:
        node = ET.Element("timing", {"enabled": str(enable_timing).lower()})
        node.text = timingpath
        root.append(node)

    if sx != None and sy != None:
        for child in root.findall("geometry"):
            child.attrib["sizeX"] = str(sx)
            child.attrib["sizeY"] = str(sy)
            child.attrib["sizeZ"] = str(sz)

    for child in root.findall("geometry"):
        attrs = child.attrib

        if "obstacle" in attrs and os.path.isfile(attrs["obstacle"]):
            shutil.copyfile(attrs["obstacle"], geometrypath)
            child.attrib["obstacle"] = geometrypath

    for child in root.findall("restart"):
        attrs = child.attrib

        if "in" in attrs and os.path.isfile(attrs["in"] + ".bak"):
            shutil.copyfile(attrs["in"] + ".bak", initial + ".bak")
            child.attrib["in"] = initial

        if "out" in attrs:
            child.attrib["out"] = bakspath + "//" + child.attrib["out"]

    tree.write(out)


PARTITIONS = {"intel": ("snb", 16, 2), "amd": ("bdz", 64, 1)}


def createJob(out, outfile, outdir, name, scenario, architecture, nranks,
              email, nspath, time):
    (partition, ppn, cpt) = PARTITIONS[architecture]

    job = JOB_TEMPLATE.format(out_file=outfile,
                              out_dir=outdir,
                              name=name,
                              partition=partition,
                              mpi_num_ranks=nranks,
                              cpus_per_task=cpt,
                              notification_email=email,
                              time=time,
                              processes_per_node=ppn,
                              ns_executable=nspath,
                              scenario=scenario)

    with open(out, "w") as outfile:
        outfile.write(job)


def submitJob(jobpath, logfile):
    code = subprocess.call(["sbatch", jobpath], stdout=logfile, stderr=logfile)

    return code == 0


def runlocal(nranks, executable, scenario):
    if nranks > 1:
        command = ["mpiexec", "-np", str(nranks), executable, scenario]
    else:
        command = [executable, scenario]

    code = subprocess.call(command, stdout=sys.stdout, stderr=sys.stdout)
    return code == 0


def main():
    options = parseArguments()

    options.out = os.path.realpath(options.out)

    if not os.path.isdir(options.out):
        os.makedirs(options.out)

    t = time.strptime(options.time, "%H:%M")
    maxTime = time.strftime("%H:%M:00", t)

    log = os.path.join(options.out, "log")
    outpath = os.path.join(options.out, "out")
    jobpath = os.path.join(options.out, "job.cmd")
    scenario = os.path.join(options.out, "scenario.xml")
    geometry = os.path.join(options.out, "geometry.geo")
    initial = os.path.join(options.out, "initial")
    initialp= os.path.join(options.out, "baks")
    vtkpath = os.path.join(options.out, "vtks")
    timingpath = os.path.join(options.out, "timing", "")

    if not os.path.isdir(initialp):
        os.mkdir(initialp)

    if not os.path.isdir(vtkpath):
        os.mkdir(vtkpath)

    if not os.path.isdir(timingpath):
        os.mkdir(timingpath)

    with open(log, "w") as logfile:
        copyPetscArguments(options.out, options.petsc_args)

        configureScenario(scenario, options.scenario, geometry, options.nx,
                          options.ny, options.nz, options.sx, options.sy,
                          options.sz, vtkpath, options.timing, timingpath,
                          options.vtk,initial,initialp)

        nranks = options.nx * options.ny * options.nz

        if options.local:
            runlocal(nranks, os.path.realpath(options.executable), scenario)
        else:
            createJob(jobpath, outpath, options.out, options.name, scenario,
                      options.architecture, nranks, options.email,
                      os.path.realpath(options.executable), maxTime)

            submitJob(jobpath, logfile)


if __name__ == "__main__":
    main()
